In [71]:
import numpy as np
import pandas as pd

In [72]:
data = pd.read_csv('cleaned.csv')
data.head()

   Area in Sqrt  No.of Bhk    Location     Price
0          3720          4  Sector 107    3.9 Cr
1          1625          3   Sector 50   1.15 Cr
2          1325          3  Sector 120      60 L
3           650          1   Sector 73      19 L
4           950          2       other   25.99 L

In [73]:
def convert_price(x):
    x = str(x).lower().strip()

    if 'cr' in x or 'crore' in x:
        num = float(x.split()[0])
        return num * 10000000   

    elif 'l' in x or 'lakh' in x:
        num = float(x.split()[0])
        return num * 100000     

    else:
        return None

data['price_rupees'] = data['Price'].apply(convert_price)

data['price_per_sqft'] = data['price_rupees'] / data['Area in Sqrt']

In [78]:
data['price_rupees']=data['price_rupees'].astype(int)

In [84]:
data.head()

,Area in Sqrt,No.of Bhk,Location,price_rupees,price_per_sqft,area_per_bhk
0,3720,4,Sector 107,39000000,10483.870968,930.000000
1,1625,3,Sector 50,11500000,7076.923077,541.666667
2,1325,3,Sector 120,6000000,4528.301887,441.666667
3,650,1,Sector 73,1900000,2923.076923,650.000000
4,950,2,other,2599000,2735.789474,475.000000

In [81]:
data = data.drop(columns='Price')

In [83]:
data['area_per_bhk'] = data['Area in Sqrt'] / data['No.of Bhk']

In [85]:
data.to_csv('cleaned1.csv',index=False)